[project]
name = "flight-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catslogs",
    "dotenv>=0.9.9",
    "kaleido==0.2.1",
    "matplotlib>=3.10.8",
    "pillow>=12.1.1",
]

[tool.uv.sources]
catslogs = { path = "lib/cats-logs" }

[tool.uv.extra-build-dependencies]
pandas = ["setuptools"]
